{{- if .Values.hbbs.oauth2 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hbbs-oauth2
  labels:
    app.kubernetes.io/name: hbbs
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  oauth2.toml: |
    {{- .Values.hbbs.oauth2 | nindent 4 }}
{{- end }}
