apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustdesk.componentName" (dict "context" . "component" "hbbs") }}
  labels:
    {{- include "rustdesk.labels" (dict "context" . "component" "hbbs") | nindent 4 }}
spec:
  selector:
    {{- include "rustdesk.selectorLabels" (dict "context" . "component" "hbbs") | nindent 4 }}
  ports:
    - name: ws
      port: 21118
      targetPort: ws
      protocol: TCP
