{{- if .Values.hbbs.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rustdesk.componentName" (dict "context" . "component" "hbbs") }}-data
  labels:
    {{- include "rustdesk.labels" (dict "context" . "component" "hbbs") | nindent 4 }}
spec:
  accessModes: {{ .Values.hbbs.persistence.accessModes | toJson }}
  {{- if .Values.hbbs.persistence.storageClass }}
  storageClassName: {{ .Values.hbbs.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.hbbs.persistence.size }}
{{- end }}
