apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustdesk.componentName" (dict "context" . "component" "webclient") }}
  labels:
    {{- include "rustdesk.labels" (dict "context" . "component" "webclient") | nindent 4 }}
spec:
  selector:
    {{- include "rustdesk.selectorLabels" (dict "context" . "component" "webclient") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
